server {
    listen 80;
    server_name _;
    absolute_redirect off;

    location = / {
        return 302 /react-antd-admin/;
    }

    location /react-antd-admin/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /react-antd-admin/index.html;
    }
}
